-- ============================================================================
-- UAT cleanup: remove all ProductBarcodes generated by mistake.
-- Assumption (confirmed by user): no scans or operations performed against
-- these barcodes, so no ScanRecords / WalletTransactions / Redemptions exist.
--
-- The script asserts this before deleting and aborts if any related rows
-- are found, so it is safe to re-run.
--
-- HOW TO USE
--   1. Run as-is. It opens a transaction, prints before/after counts, then
--      ROLLBACKs at the bottom so you can verify nothing else got touched.
--   2. If the counts look right, change the final ROLLBACK TRAN to
--      COMMIT TRAN and run the script again.
-- ============================================================================

SET XACT_ABORT ON;
SET NOCOUNT ON;

BEGIN TRY
    BEGIN TRAN;

    -- Safety assertion: refuse to run if any related rows exist
    DECLARE @scans INT          = (SELECT COUNT(*) FROM ScanRecords);
    DECLARE @walletTx INT       = (SELECT COUNT(*) FROM WalletTransactions);
    DECLARE @redemptions INT    = (SELECT COUNT(*) FROM RedemptionRequests);

    IF @scans > 0 OR @walletTx > 0 OR @redemptions > 0
    BEGIN
        PRINT '=== ABORT: related rows present ===';
        PRINT 'ScanRecords:        ' + CAST(@scans AS VARCHAR);
        PRINT 'WalletTransactions: ' + CAST(@walletTx AS VARCHAR);
        PRINT 'RedemptionRequests: ' + CAST(@redemptions AS VARCHAR);
        PRINT 'The user stated nothing has been scanned. Investigate before';
        PRINT 'running this script with the cascading-delete variant.';
        ROLLBACK TRAN;
        RETURN;
    END;

    DECLARE @barcodesBefore INT = (SELECT COUNT(*) FROM ProductBarcodes);
    PRINT '=== BEFORE ===';
    PRINT 'ProductBarcodes: ' + CAST(@barcodesBefore AS VARCHAR);

    DELETE FROM ProductBarcodes;

    DECLARE @barcodesAfter INT = (SELECT COUNT(*) FROM ProductBarcodes);
    PRINT '=== AFTER ===';
    PRINT 'ProductBarcodes: ' + CAST(@barcodesAfter AS VARCHAR);
    PRINT 'Deleted: ' + CAST((@barcodesBefore - @barcodesAfter) AS VARCHAR);

    -- Default safety: roll back. Change to COMMIT TRAN once verified.
    ROLLBACK TRAN;
    -- COMMIT TRAN;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    THROW;
END CATCH;
