using FluentAssertions;
using RewardProgram.Domain.Entities.Users;
using RewardProgram.Domain.Enums.UserEnums;

namespace RewardProgram.Domain.Tests;

public class ApplicationUserTests
{
    [Fact]
    public void NewUser_ShouldHave_AutoGeneratedGuidId()
    {
        var user = new ApplicationUser();

        user.Id.Should().NotBeNullOrEmpty();
        Guid.TryParse(user.Id, out _).Should().BeTrue();
    }

    [Fact]
    public void NewUser_ShouldHave_AutoGeneratedSecurityStamp()
    {
        var user = new ApplicationUser();

        user.SecurityStamp.Should().NotBeNullOrEmpty();
        Guid.TryParse(user.SecurityStamp, out _).Should().BeTrue();
    }

    [Fact]
    public void TwoUsers_ShouldHave_DifferentIds()
    {
        var u1 = new ApplicationUser();
        var u2 = new ApplicationUser();

        u1.Id.Should().NotBe(u2.Id);
    }

    [Fact]
    public void NewUser_ShouldHave_CreatedAtSetToUtcNow()
    {
        var before = DateTime.UtcNow;
        var user = new ApplicationUser();
        var after = DateTime.UtcNow;

        user.CreatedAt.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }

    [Fact]
    public void NewUser_ShouldHave_DefaultValues()
    {
        var user = new ApplicationUser();

        user.IsDisabled.Should().BeFalse();
        user.Name.Should().BeEmpty();
        user.MobileNumber.Should().BeEmpty();
        user.ProfileImageUrl.Should().BeNull();
        user.InvitationCode.Should().BeNull();
        user.InvitedByUserId.Should().BeNull();
        user.AssignedSalesManId.Should().BeNull();
        user.NationalAddress.Should().BeNull();
    }

    [Fact]
    public void NewUser_ShouldHave_EmptyCollections()
    {
        var user = new ApplicationUser();

        user.RefreshTokens.Should().BeEmpty();
        user.AssignedUsers.Should().BeEmpty();
        user.ApprovalRecords.Should().BeEmpty();
        user.ApprovalCities.Should().BeEmpty();
    }
}
