using FluentAssertions;
using RewardProgram.Domain.Entities;

namespace RewardProgram.Domain.Tests;

// Concrete subclass for testing the abstract TrackableEntity
public class TestEntity : TrackableEntity { }

public class TrackableEntityTests
{
    [Fact]
    public void NewEntity_ShouldHave_AutoGeneratedGuidV7Id()
    {
        var entity = new TestEntity();

        entity.Id.Should().NotBeNullOrEmpty();
        Guid.TryParse(entity.Id, out _).Should().BeTrue();
    }

    [Fact]
    public void NewEntity_ShouldHave_CreatedAtSetToUtcNow()
    {
        var before = DateTime.UtcNow;
        var entity = new TestEntity();
        var after = DateTime.UtcNow;

        entity.CreatedAt.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }

    [Fact]
    public void NewEntity_ShouldHave_IsDeletedFalse()
    {
        var entity = new TestEntity();

        entity.IsDeleted.Should().BeFalse();
    }

    [Fact]
    public void NewEntity_ShouldHave_NullAuditFields()
    {
        var entity = new TestEntity();

        entity.CreatedBy.Should().BeNull();
        entity.UpdatedAt.Should().BeNull();
        entity.UpdatedBy.Should().BeNull();
        entity.DeletedAt.Should().BeNull();
        entity.DeletedBy.Should().BeNull();
    }

    [Fact]
    public void TwoEntities_ShouldHave_DifferentIds()
    {
        var entity1 = new TestEntity();
        var entity2 = new TestEntity();

        entity1.Id.Should().NotBe(entity2.Id);
    }
}
